### ISSUE TITLE
Plugin Execution Error

### ISSUE THREAD

**Issue by cjgates11** [bguidinger/Xrm.ReportRenderer#50]
Hi Bob,

I wonder if you can help?

We're using report renderer for a client and have started getting an issue in flow with solution version 1.5

I thought there might be an issue with environments and connections etc in Flow itself so have created a new flow in the correct environment.  The app registration secret has been renewed and the connection seems to be fine.  So is the API access to CDS for the environment.  The connection seems to be fine as we are seeing plug in execution exceptions being created so it looks like flow is able to connect with no issues.. See below.  I also refreshed the credentials in the solution configuration.

I wonder if you have any ideas about what is going on?

Cheers

Chris.

Flow reports an error when rendering a report

Something went wrong: Error executing web request: https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&Format=PDF&ContentDisposition=AlwaysAttachment&FileName=&Culture=1033&CultureOverrides=False&UICulture=1033&UICultureOverrides=False&ReportSession=repl51vgqoms4g3fjynorp45&ControlID=e3c488bbc8ec4afa94e475815b7e1e2b

There is also a plug in execution error in CRM

Unhandled exception:
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Something went wrong: Error executing web request: https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&Format=PDF&ContentDisposition=AlwaysAttachment&FileName=&Culture=1033&CultureOverrides=False&UICulture=1033&UICultureOverrides=False&ReportSession=repl51vgqoms4g3fjynorp45&ControlID=4f471065789148038c6ca740209cd17dDetail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>ca90607f-9b74-4a4c-867f-5b12a8abd0c1</ActivityId>
<ErrorCode>-2147220891</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
<KeyValuePairOfstringanyType>
<d2p1:key>OperationStatus</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">0</d2p1:value>
</KeyValuePairOfstringanyType>
<KeyValuePairOfstringanyType>
<d2p1:key>SubErrorCode</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">-2146233088</d2p1:value>
</KeyValuePairOfstringanyType>
</ErrorDetails>
<HelpLink i:nil="true" />
<Message>Something went wrong: Error executing web request: https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&amp;Format=PDF&amp;ContentDisposition=AlwaysAttachment&amp;FileName=&amp;Culture=1033&amp;CultureOverrides=False&amp;UICulture=1033&amp;UICultureOverrides=False&amp;ReportSession=repl51vgqoms4g3fjynorp45&amp;ControlID=4f471065789148038c6ca740209cd17d</Message>
<Timestamp>2020-07-15T11:05:03.5806393Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault>
<ActivityId>ca90607f-9b74-4a4c-867f-5b12a8abd0c1</ActivityId>
<ErrorCode>-2147220970</ErrorCode>
<ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink i:nil="true" />
<Message>System.Exception: Error executing web request: https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&amp;Format=PDF&amp;ContentDisposition=AlwaysAttachment&amp;FileName=&amp;Culture=1033&amp;CultureOverrides=False&amp;UICulture=1033&amp;UICultureOverrides=False&amp;ReportSession=repl51vgqoms4g3fjynorp45&amp;ControlID=4f471065789148038c6ca740209cd17d
at BGuidinger.Reports.Renderer.GetResponse(HttpWebRequest request)
at BGuidinger.Reports.Renderer.RenderReport(Entity report, String format, String parameters)
at BGuidinger.Reports.Render.OnExecute(IPluginProvider provider)
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #20E22317</Message>
<Timestamp>2020-07-15T11:05:03.5806393Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource i:nil="true" />
<InnerFault i:nil="true" />
<OriginalException i:nil="true" />
<TraceText i:nil="true" />
</InnerFault>
<OriginalException>Microsoft.Xrm.Sdk.InvalidPluginExecutionException
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass15_0.&lt;Execute&gt;b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage)
at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException>
<TraceText>
2020-07-15 11:05:02.033 - Starting execution.
2020-07-15 11:05:02.033 - Authenticating....
2020-07-15 11:05:02.158 - Authenticated.
2020-07-15 11:05:02.174 - POST https://esuoms.crm4.dynamics.com/CRMReports/RSViewer/ReportViewer.aspx
2020-07-15 11:05:02.174 - id=%7Bdf7d126f-f4fb-e911-a813-000d3ab8d5b5%7D&amp;iscustomreport=true&amp;reportnameonsrs=&amp;p:Branch=%7B28e6e6c9-6a43-e911-a83a-000d3ab86580%7D
2020-07-15 11:05:03.518 - GET https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&amp;Format=PDF&amp;ContentDisposition=AlwaysAttachment&amp;FileName=&amp;Culture=1033&amp;CultureOverrides=False&amp;UICulture=1033&amp;UICultureOverrides=False&amp;ReportSession=repl51vgqoms4g3fjynorp45&amp;ControlID=4f471065789148038c6ca740209cd17d
2020-07-15 11:05:03.580 - Parm0: Error Details: The report execution repl51vgqoms4g3fjynorp45 has expired or cannot be found.
2020-07-15 11:05:03.580 - Error executing web request: https://esuoms.crm4.dynamics.com/Reserved.ReportViewerWebControl.axd?OpType=Export&amp;Format=PDF&amp;ContentDisposition=AlwaysAttachment&amp;FileName=&amp;Culture=1033&amp;CultureOverrides=False&amp;UICulture=1033&amp;UICultureOverrides=False&amp;ReportSession=repl51vgqoms4g3fjynorp45&amp;ControlID=4f471065789148038c6ca740209cd17d
2020-07-15 11:05:03.580 - Stopping execution.
</TraceText>
</OrganizationServiceFault>

Any help much appreciated.

Cheers

Chris.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
