### ISSUE TITLE
Plugin Execution Exception - Authentication

### ISSUE THREAD

**Issue by drissenberg** [bguidinger/Xrm.ReportRenderer#51]
Hi Bob,

I'm getting a plugin exception for bg_Render.  It seems simply to be an authentication issue.  The SecureConfiguration setting is in place and looks fine.  Here is the message block from the step and the exception details.  Many thanks for any help.

David

2020-07-15 16:00:00.590 - Starting execution.
2020-07-15 16:00:00.606 - Authenticating....
2020-07-15 16:00:01.027 - The remote server returned an error: (400) Bad Request.
2020-07-15 16:00:01.027 - Stopping execution.

Unhandled exception:
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Something went wrong: The remote server returned an error: (400) Bad Request.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>f3d6501d-1b0a-453d-a80a-1154b81c71a0</ActivityId>
<ErrorCode>-2147220891</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
<KeyValuePairOfstringanyType>
<d2p1:key>OperationStatus</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">0</d2p1:value>
</KeyValuePairOfstringanyType>
<KeyValuePairOfstringanyType>
<d2p1:key>SubErrorCode</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">-2146233088</d2p1:value>
</KeyValuePairOfstringanyType>
</ErrorDetails>
<HelpLink i:nil="true" />
<Message>Something went wrong: The remote server returned an error: (400) Bad Request.</Message>
<Timestamp>2020-07-15T16:00:01.0279426Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault>
<ActivityId>f3d6501d-1b0a-453d-a80a-1154b81c71a0</ActivityId>
<ErrorCode>-2147220970</ErrorCode>
<ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink i:nil="true" />
<Message>System.Net.WebException: The remote server returned an error: (400) Bad Request.
at System.Net.HttpWebRequest.GetResponse()
at BGuidinger.Reports.Renderer.GetToken(String resource, String username, String password)
at BGuidinger.Reports.Renderer.Authenticate(String resource, String username, String password)
at BGuidinger.Reports.Render.OnExecute(IPluginProvider provider)
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #4124366D</Message>
<Timestamp>2020-07-15T16:00:01.0279426Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource i:nil="true" />
<InnerFault i:nil="true" />
<OriginalException i:nil="true" />
<TraceText i:nil="true" />
</InnerFault>
<OriginalException>Microsoft.Xrm.Sdk.InvalidPluginExecutionException
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass15_0.&lt;Execute&gt;b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage)
at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException>
<TraceText>
2020-07-15 16:00:00.590 - Starting execution.
2020-07-15 16:00:00.606 - Authenticating....
2020-07-15 16:00:01.027 - The remote server returned an error: (400) Bad Request.
2020-07-15 16:00:01.027 - Stopping execution.
</TraceText>
</OrganizationServiceFault>

**Comment by bguidinger** [comment]
@drissenberg which region is your CRM instance in?  Does the account you're using have MFA enabled?  Are you trying to use an application user (client ID/client secret)?

**Comment by kmturek** [comment]
having the same exact issues, was working just fine, then we updated to V9.1 and I cant get a POST response. We are not using MFA and are located in Northern America

**Comment by kmturek** [comment]
I checked the plugin and its secured with user name and password as well

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
