### ISSUE TITLE
Custom Action Execution Exception - Authentication Problem

### ISSUE THREAD

**Issue by abrookie** [bguidinger/Xrm.ReportRenderer#52]
Hi Bob,

I'm getting a exception for the bg_Render custom action. It seems simply to be an authentication issue. The SecureConfiguration setting with my user name and credentials is in place and looks fine. Here is the message block from the step and the exception details. I'm not using Client ID / Client Secret, I am using my normal Dynamics 365 user id / password.  I'm also not trying to call it from a Flow, just trying to call the custom action directly.

Any help would be appreciated.

Austin

Unhandled exception:
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Something went wrong: The remote server returned an error: (400) Bad Request.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>a6c01c93-a221-4f7c-886c-5a6c5caffd2c</ActivityId>
<ErrorCode>-2147220891</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
<KeyValuePairOfstringanyType>
<d2p1:key>OperationStatus</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">0</d2p1:value>
</KeyValuePairOfstringanyType>
<KeyValuePairOfstringanyType>
<d2p1:key>SubErrorCode</d2p1:key>
<d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int">-2146233088</d2p1:value>
</KeyValuePairOfstringanyType>
</ErrorDetails>
<HelpLink i:nil="true" />
<Message>Something went wrong: The remote server returned an error: (400) Bad Request.</Message>
<Timestamp>2020-11-10T16:05:41.1457299Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource>PluginExecution</ExceptionSource>
<InnerFault>
<ActivityId>a6c01c93-a221-4f7c-886c-5a6c5caffd2c</ActivityId>
<ErrorCode>-2147220970</ErrorCode>
<ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<HelpLink i:nil="true" />
<Message>System.Net.WebException: The remote server returned an error: (400) Bad Request.
at System.Net.HttpWebRequest.GetResponse()
at BGuidinger.Reports.Renderer.GetToken(String resource, String username, String password)
at BGuidinger.Reports.Renderer.Authenticate(String resource, String username, String password)
at BGuidinger.Reports.Render.OnExecute(IPluginProvider provider)
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #367F8E5A</Message>
<Timestamp>2020-11-10T16:05:41.1457299Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource i:nil="true" />
<InnerFault i:nil="true" />
<OriginalException i:nil="true" />
<TraceText i:nil="true" />
</InnerFault>
<OriginalException>Microsoft.Xrm.Sdk.InvalidPluginExecutionException
at BGuidinger.Base.Plugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.&lt;&gt;c__DisplayClass17_0.&lt;Execute&gt;b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain, String crashOnPluginExceptionMessage)
at Microsoft.Crm.Sandbox.SandboxWorker.&lt;&gt;c__DisplayClass3_0.&lt;Execute&gt;b__0()</OriginalException>
<TraceText>
2020-11-10 16:05:39.380 - Starting execution.
2020-11-10 16:05:39.864 - Authenticating....
2020-11-10 16:05:41.145 - The remote server returned an error: (400) Bad Request.
2020-11-10 16:05:41.145 - Stopping execution.
</TraceText>
</OrganizationServiceFault>

**Comment by abrookie** [comment]
This CRM is the West Region

**Comment by aloncor** [comment]
I'm having the same issue, checking the code I have a doubt why the client id is hardcoded like in the following image:

![image](https://user-images.githubusercontent.com/18650162/103423869-45d96a80-4b77-11eb-87a5-c84d39e08b9d.png)

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
